export { default as allTeachers } from './all-teachers'
export { default as createTeacher } from './create-teacher'
export { default as deleteTeacher } from './delete-teacher'
export { default as updateTeacher } from './update-teacher'
export { default as teacherGroups } from './get-groups'
export { default as teacherDetails } from './teacher-details'