@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicm9vdCIsInBlcm1pc3Npb25zIjpbImFkbWluIl0sImlhdCI6MTY3NTA3MzQ4NiwiZXhwIjoxNjc1MjQ2Mjg2fQ.fZaD2aDPX6dW8fGkFWolR8ps_NPFK_eETzaulQeJeQc
@teacherToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiYWxpbW92IiwicGVybWlzc2lvbnMiOlsidGVhY2hlciJdLCJpYXQiOjE2NzQ3NDgxODcsImV4cCI6MTY3NDc2MjU4N30.AL11LHi-GEjEM7nVxu4OOQgFLN9GKft9_hyK2XA4MK8

POST http://neowise.uz:3115/api/v1/auth/login
Content-Type: application/json

{
   "username": "root", 
   "password": "1234"
}

###

POST http://neowise.uz:3115/api/v1/admins
Content-Type: application/json

{
   "name": "Administrator",
   "username": "root", 
   "password": "1234",
   "permissions": ["admin"]
}

###

POST http://neowise.uz:3115/api/v1/teachers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicm9vdCIsInBlcm1pc3Npb25zIjpbImFkbWluIl0sImlhdCI6MTY3NDc0Nzk5OCwiZXhwIjoxNjc0NzYyMzk4fQ.dndFLE2CKw7P7QY0WkM69mjStv1Oo8Pc5RFtN6Iw0kQ
Content-Type: application/json

{
    "username": "alimov",
    "password": "1234",
    "name": "Kamron",
    "surname": "Alimov",
    "birthday": "08-09-1997",
    "phone": "99899565121",
    "directions": [1]
}