@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicm9vdCIsInBlcm1pc3Npb25zIjpbImFkbWluIl0sImlhdCI6MTY3NTA3MzQ4NiwiZXhwIjoxNjc1MjQ2Mjg2fQ.fZaD2aDPX6dW8fGkFWolR8ps_NPFK_eETzaulQeJeQc

POST http://neowise.uz:3115/api/v1/directions
Authorization: {{adminToken}}
Content-Type: application/json

{
    "name": "Node.js"
}

###

GET http://localhost:1900/api/v1/dashboard
Authorization: {{adminToken}}
