export { default as allStudents } from './all-students'
export { default as createStudent } from './create-student'
export { default as deleteStudent } from './delete-student'
export { default as updateStudent } from './update-student'
export { default as studentGroups } from './student-groups'
export { default as studentDetails } from './student-details'