export { default as allAdmins } from './all-admins'
export { default as createAdmin } from './create-admin'
export { default as deleteAdmin } from './delete-admin'
export { default as recoverAdmin } from './recover-admin'
export { default as updateAdmin } from './update-admin'
export { default as getAdmin } from './get-admin'
export { default as adminDetails } from './admin-details'